# Generated by Django 3.1 on 2020-08-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trveller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
